set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)
find_package(UHD REQUIRED)
add_library(uhd INTERFACE)
target_include_directories(uhd INTERFACE ${UHD_INCLUDE_DIRS})
target_link_libraries(uhd INTERFACE ${UHD_LIBRARIES})
set(CSICS_USE_UHD ON)
if (CSICS_UHD_VENDORED)
    message(STATUS "Using vendored UHD library.")
else()
    message(STATUS "Using system-installed UHD library.")
endif()
